apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-sql
  namespace: bitwarden
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sql
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /var/nfs/k8s/bitwarden/sql
    server: master1