apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-data
  namespace: bitwarden
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: data
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /var/nfs/k8s/bitwarden/data
    server: master1