apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-data
  namespace: bitwarden
spec:
  storageClassName: data
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi