apiVersion: v1
kind: ConfigMap
metadata:
  name: bitwarden-global-config
  namespace: bitwarden
data:
  ASPNETCORE_ENVIRONMENT: Production
  globalSettings__selfHosted: "true"
  globalSettings__baseServiceUri__internalNotifications: "http://bitwarden-notifications"
  globalSettings__baseServiceUri__internalAdmin: "http://bitwarden-admin"
  globalSettings__baseServiceUri__internalIdentity: "http://bitwarden-identity"
  globalSettings__baseServiceUri__internalApi: "http://bitwarden-api"
  globalSettings__baseServiceUri__internalVault: "http://bitwarden-web"
  globalSettings__baseServiceUri__internalSso: "http://bitwarden-sso"
  globalSettings__baseServiceUri__internalPortal: "http://bitwarden-portal"
  globalSettings__pushRelayBaseUri: "https://push.bitwarden.com"
  globalSettings__installation__identityUri: "https://identity.bitwarden.com"
  globalSettings__baseServiceUri__vault: "https://bitwarden.example.com"
  globalSettings__baseServiceUri__api: "https://bitwarden.example.com/api"
  globalSettings__baseServiceUri__identity: "https://bitwarden.example.com/identity"
  globalSettings__baseServiceUri__admin: "https://bitwarden.example.com/admin"
  globalSettings__baseServiceUri__notifications: "https://bitwarden.example.com/notifications"
  globalSettings__baseServiceUri__sso: "https://bitwarden.example.com/sso"
  globalSettings__baseServiceUri__portal: "https://bitwarden.example.com/portal"
  globalSettings__sqlServer__connectionString: "Data Source: tcp:bitwarden-mssql,1433;Initial Catalog: vault;Persist Security Info: False;User ID: sa;Password: RANDOM_DATABASE_PASSWORD;MultipleActiveResultSets: False;Connect Timeout: 30;Encrypt: True;TrustServerCertificate: True"
  globalSettings__identityServer__certificatePassword: "IDENTITY_CERT_PASSWORD"
  globalSettings__attachment__baseDirectory: "/etc/bitwarden/core/attachments"
  globalSettings__attachment__baseUrl: "https://bitwarden.example.com/attachments"
  globalSettings__send__baseDirectory: "/etc/bitwarden/core/attachments/send"
  globalSettings__send__baseUrl: "https://bitwarden.example.com/attachments/send"
  globalSettings__dataProtection__directory: "/etc/bitwarden/core/aspnet-dataprotection"
  globalSettings__logDirectory: "/etc/bitwarden/logs"
  globalSettings__logRollBySizeLimit: ""
  globalSettings__syslog__destination: ""
  globalSettings__licenseDirectory: "/etc/bitwarden/core/licenses"
  globalSettings__internalIdentityKey: "RANDOM_IDENTITY_KEY"
  globalSettings__oidcIdentityClientKey: "RANDOM_IDENTITY_KEY"
  globalSettings__duo__aKey: "RANDOM_DUO_AKEY"
  globalSettings__installation__id: "00000000-0000-0000-0000-000000000000"
  globalSettings__installation__key: "SECRET_INSTALLATION_KEY"
  globalSettings__yubico__clientId: "REPLACE"
  globalSettings__yubico__key: "REPLACE"
  globalSettings__mail__replyToEmail: "no-reply@bitwarden.example.com"
  globalSettings__mail__smtp__host: "REPLACE"
  globalSettings__mail__smtp__port: "587"
  globalSettings__mail__smtp__ssl: "false"
  globalSettings__mail__smtp__username: "REPLACE"
  globalSettings__mail__smtp__password: "REPLACE"
  globalSettings__disableUserRegistration: "false"
  globalSettings__hibpApiKey: "REPLACE"
  adminSettings__admins: ""