apiVersion: v1
kind: Secret
metadata:
  name: azure-file-secret
  namespace: default
type: Opaque
data:
  azurestorageaccountname: <base64 encoded storage account name>
  azurestorageaccountkey: <base64 encoded storage account key>