apiVersion: v1
kind: PersistentVolume
metadata:
  name: azure-bitwarden-data
  # The label is used for matching the exact claim
  labels:
    usage: azure-bitwarden-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  azureFile:
    # Replace with your secret name
    secretName: azure-file-secret
    # Replace with correct storage share name
    shareName: bitwarden-data
    # In case the secret is stored in a different namespace
    secretNamespace: default
    readOnly: false